# Generated by Django 2.2.10 on 2021-04-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_useranswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='user',
            field=models.IntegerField(verbose_name='id пользователя'),
        ),
    ]
